// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyBQAbf0HzmBbW6cbf0ZBXZwkdpHagubYgs',
  //   appId: '1:542022981816:web:d25f676c1f5b1a9bfebc4d',
  //   messagingSenderId: '542022981816',
  //   projectId: 'datingapp-e2c9e',
  //   authDomain: 'datingapp-e2c9e.firebaseapp.com',
  //   storageBucket: 'datingapp-e2c9e.appspot.com',
  //   measurementId: 'G-DF4JBYX49L',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_7a6-gHIuDeJFFd02B4HU59hk6f7InI',
    appId: '1:542022981816:android:03986e14e8225ef5febc4d',
    messagingSenderId: '542022981816',
    projectId: 'datingapp-e2c9e',
    storageBucket: 'datingapp-e2c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYVPNasQWcc1zwdkPrOznExfjs0KNeeSo',
    appId: '1:542022981816:ios:ef86f3e763d3834bfebc4d',
    messagingSenderId: '542022981816',
    projectId: 'datingapp-e2c9e',
    storageBucket: 'datingapp-e2c9e.appspot.com',
    iosBundleId: 'com.example.datingapp',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAYVPNasQWcc1zwdkPrOznExfjs0KNeeSo',
  //   appId: '1:542022981816:ios:5bc8b6cef2edd30efebc4d',
  //   messagingSenderId: '542022981816',
  //   projectId: 'datingapp-e2c9e',
  //   storageBucket: 'datingapp-e2c9e.appspot.com',
  //   iosBundleId: 'com.example.datingapp.RunnerTests',
  // );
}
